version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"

  pre_build:
    commands:
      - echo "Starting Build"

  build:
    commands:
      - echo "Building Application"
      - ls -la

  post_build:
    commands:
      - echo "Build Completed Successfully"

artifacts:
  files:
    - '**/*'